# Generated by Django 3.0.1 on 2021-08-05 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_wishlistitem_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['-date_created']},
        ),
    ]
