version: '3'

services: 
    web:
        build: .
        #command: python manage.py runserver 0.0.0.0:8000
        command: gunicorn bookstore_project.wsgi -b 0.0.0.0:8000  # using gunicorn gateway
        environment: 
            - ENVIRONMENT=development
            - NEW_SECRET_KEY=-rn%f8dsn4qey_9-_7+3&ukru2+th&q@c@y7pn@+d3gyhcohpn
            - DEBUG=1
            - FLUTTERWAVE_PUBLIC_TEST_KEY=FLWPUBK_TEST-1127e42965606338d685d420b8907504-X
            - FLUTTERWAVE_SECRET_TEST_KEY=FLWSECK_TEST-7e3f9ff0b0d6ef64ed88be500eb2d87c-X

        volumes: 
            - .:/code
        ports: 
            - 8000:8000
        depends_on: 
            - db
            - es
    
    db:
        image: postgres
        volumes: 
            - ./data/db:/var/lib/postgresql/data
        environment: 
            - POSTGRES_DB=bookstore_db
            - POSTGRES_USER=skydata
            - POSTGRES_PASSWORD=12345678
        
        
    
    es:
        image: elasticsearch:7.8.1
        environment: 
            - discovery.type=single-node
        ports: 
            - "9200:9200"