version: '3'

services: 
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        environment: 
            - NEW_SECRET_KEY=-rn%f8dsn4qey_9-_7+3&ukru2+th&q@c@y7pn@+d3gyhcohpn
            - DEBUG=1
        volumes: 
            - .:/code
        ports: 
            - 8000:8000
        depends_on: 
            - db
    
    db:
        image: postgres
        volumes: 
            - ./data/db:/var/lib/postgresql/data
        environment: 
            - POSTGRES_DB=bookstore_db
            - POSTGRES_USER=skydata
            - POSTGRES_PASSWORD=12345678