# Generated by Django 3.0.1 on 2021-07-09 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.Genre'),
        ),
    ]
