# Generated by Django 3.0.1 on 2021-07-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='slug', max_length=150),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='slug', max_length=200),
        ),
    ]
