# Generated by Django 3.0.1 on 2021-07-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20210709_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=150), max_length=150),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=200), max_length=200),
        ),
    ]
