# Generated by Django 3.0.1 on 2021-08-05 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_created']},
        ),
    ]
