# Generated by Django 3.0.1 on 2021-07-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210720_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
